// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE6EByjzVTIBd_IvUX1r3x5PPVCiUdR9U',
    appId: '1:630750521691:web:d447727e6ca9de37a9127e',
    messagingSenderId: '630750521691',
    projectId: 'flower-app-cc183',
    authDomain: 'flower-app-cc183.firebaseapp.com',
    storageBucket: 'flower-app-cc183.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpU_5V_LMOLaYPo-grzeHbDMPEXIBlJhY',
    appId: '1:630750521691:android:873fb43e33a535f3a9127e',
    messagingSenderId: '630750521691',
    projectId: 'flower-app-cc183',
    storageBucket: 'flower-app-cc183.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCev0h8s6UAsUupZG0z-kQjBYZ4UwQDVEk',
    appId: '1:630750521691:ios:d6c9ede41ca37affa9127e',
    messagingSenderId: '630750521691',
    projectId: 'flower-app-cc183',
    storageBucket: 'flower-app-cc183.appspot.com',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCev0h8s6UAsUupZG0z-kQjBYZ4UwQDVEk',
    appId: '1:630750521691:ios:d6c9ede41ca37affa9127e',
    messagingSenderId: '630750521691',
    projectId: 'flower-app-cc183',
    storageBucket: 'flower-app-cc183.appspot.com',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE6EByjzVTIBd_IvUX1r3x5PPVCiUdR9U',
    appId: '1:630750521691:web:01cc24bfc8be3c9ca9127e',
    messagingSenderId: '630750521691',
    projectId: 'flower-app-cc183',
    authDomain: 'flower-app-cc183.firebaseapp.com',
    storageBucket: 'flower-app-cc183.appspot.com',
  );
}
